<script lang="ts">
    import { TrendingUp, HandCoins } from "@lucide/svelte";
    import { Doughnut } from "svelte-chartjs";

    let {
        timeHorizonYears = 30,
        contributionData = {
            totalIncome: 0,
            totalSpending: 0,
            incomeChart: null as any,
            spendingChart: null as any,
            topIncomes: [] as any[],
            topSpendings: [] as any[],
            incomeColors: [] as string[],
            spendingColors: [] as string[],
        },
        contributionChartOptions = null,
        formatGermanAmount = (v: number) => v.toFixed(2),
    } = $props<{
        timeHorizonYears: number;
        contributionData: {
            totalIncome: number;
            totalSpending: number;
            incomeChart: any;
            spendingChart: any;
            topIncomes: any[];
            topSpendings: any[];
            incomeColors: string[];
            spendingColors: string[];
        };
        contributionChartOptions: any;
        formatGermanAmount: (v: number) => string;
    }>();
</script>

<div class="grid grid-cols-1 lg:grid-cols-2 gap-12">
    <!-- Income Generation Column -->
    <div class="space-y-6">
        <div class="space-y-1">
            <h4 class="text-xs font-black uppercase tracking-[0.2em] text-slate-900 dark:text-slate-100 flex items-center gap-2">
                <TrendingUp class="w-4 h-4 text-emerald-600" />
                Income Generation
            </h4>
            <p class="text-slate-400 font-medium text-xs">
                Total revenue generated by each source over the {timeHorizonYears}-year horizon.
            </p>
        </div>

        <div class="h-[200px] relative flex items-center justify-center">
            {#if contributionData.incomeChart && contributionData.topIncomes.length > 0}
                <Doughnut data={contributionData.incomeChart} options={contributionChartOptions} />
                <div class="absolute flex flex-col items-center justify-center text-center pointer-events-none">
                    <span class="text-[9px] font-black text-slate-400 uppercase tracking-widest">Total Income</span>
                    <span class="font-black text-slate-900 dark:text-slate-100 text-lg">€{formatGermanAmount(contributionData.totalIncome)}</span>
                </div>
            {:else}
                <span class="text-slate-400 font-bold text-xs">No Income Data Projected</span>
            {/if}
        </div>

        <!-- Ranked List -->
        <div class="space-y-2.5 max-h-[250px] overflow-y-auto pr-1">
            {#each contributionData.topIncomes as income, idx}
                {@const percentage = contributionData.totalIncome > 0 ? (income.amount / contributionData.totalIncome) * 100 : 0}
                {@const color = contributionData.incomeColors[idx % contributionData.incomeColors.length]}
                <div class="flex items-center justify-between p-3 rounded-xl border border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-all shadow-sm">
                    <div class="flex items-center gap-3 min-w-0">
                        <span class="flex items-center justify-center w-5 h-5 rounded-lg text-[9px] font-black text-white" style="background-color: {color}">
                            #{idx + 1}
                        </span>
                        <span class="font-bold text-slate-700 dark:text-slate-200 text-xs truncate" title={income.name}>
                            {income.name}
                        </span>
                    </div>
                    <div class="text-right whitespace-nowrap pl-4">
                        <span class="font-black text-slate-900 dark:text-slate-100 text-xs block">€{formatGermanAmount(income.amount)}</span>
                        <span class="text-[9px] font-black text-emerald-600 block">{percentage.toFixed(1)}%</span>
                    </div>
                </div>
            {/each}
        </div>
    </div>

    <!-- Spending Consumption Column -->
    <div class="space-y-6">
        <div class="space-y-1">
            <h4 class="text-xs font-black uppercase tracking-[0.2em] text-slate-900 dark:text-slate-100 flex items-center gap-2">
                <HandCoins class="w-4 h-4 text-rose-500" />
                Spending & Savings Hotspots
            </h4>
            <p class="text-slate-400 font-medium text-xs">
                Total wealth consumed by liabilities, savings rate, and loans over the {timeHorizonYears}-year horizon.
            </p>
        </div>

        <div class="h-[200px] relative flex items-center justify-center">
            {#if contributionData.spendingChart && contributionData.topSpendings.length > 0}
                <Doughnut data={contributionData.spendingChart} options={contributionChartOptions} />
                <div class="absolute flex flex-col items-center justify-center text-center pointer-events-none">
                    <span class="text-[9px] font-black text-slate-400 uppercase tracking-widest">Total Spent</span>
                    <span class="font-black text-slate-900 dark:text-slate-100 text-lg">€{formatGermanAmount(contributionData.totalSpending)}</span>
                </div>
            {:else}
                <span class="text-slate-400 font-bold text-xs">No Spending Data Projected</span>
            {/if}
        </div>

        <!-- Ranked List -->
        <div class="space-y-2.5 max-h-[250px] overflow-y-auto pr-1">
            {#each contributionData.topSpendings as spending, idx}
                {@const percentage = contributionData.totalSpending > 0 ? (spending.amount / contributionData.totalSpending) * 100 : 0}
                {@const color = contributionData.spendingColors[idx % contributionData.spendingColors.length]}
                <div class="flex items-center justify-between p-3 rounded-xl border border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-all shadow-sm">
                    <div class="flex items-center gap-3 min-w-0">
                        <span class="flex items-center justify-center w-5 h-5 rounded-lg text-[9px] font-black text-white" style="background-color: {color}">
                            #{idx + 1}
                        </span>
                        <div class="min-w-0">
                            <span class="font-bold text-slate-700 dark:text-slate-200 text-xs block truncate pr-1" title={spending.name}>
                                {spending.name}
                            </span>
                            <span class="text-[8px] font-black text-slate-400 uppercase tracking-wider block">{spending.type}</span>
                        </div>
                    </div>
                    <div class="text-right whitespace-nowrap pl-4">
                        <span class="font-black text-slate-900 dark:text-slate-100 text-xs block">€{formatGermanAmount(spending.amount)}</span>
                        <span class="text-[9px] font-black text-rose-500 block">{percentage.toFixed(1)}%</span>
                    </div>
                </div>
            {/each}
        </div>
    </div>
</div>
