// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: execution_engine/proto/execution.proto

package executionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_execution_engine_proto_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_engine_proto_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_execution_engine_proto_execution_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_execution_engine_proto_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_engine_proto_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_execution_engine_proto_execution_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlanId         string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	StateMsgpack   []byte                 `protobuf:"bytes,3,opt,name=state_msgpack,json=stateMsgpack,proto3" json:"state_msgpack,omitempty"`
	SecretsMsgpack []byte                 `protobuf:"bytes,4,opt,name=secrets_msgpack,json=secretsMsgpack,proto3" json:"secrets_msgpack,omitempty"`
	TriggerMsgpack []byte                 `protobuf:"bytes,5,opt,name=trigger_msgpack,json=triggerMsgpack,proto3" json:"trigger_msgpack,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_execution_engine_proto_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_engine_proto_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_execution_engine_proto_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetStateMsgpack() []byte {
	if x != nil {
		return x.StateMsgpack
	}
	return nil
}

func (x *ExecuteRequest) GetSecretsMsgpack() []byte {
	if x != nil {
		return x.SecretsMsgpack
	}
	return nil
}

func (x *ExecuteRequest) GetTriggerMsgpack() []byte {
	if x != nil {
		return x.TriggerMsgpack
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	NotCached     bool                   `protobuf:"varint,5,opt,name=not_cached,json=notCached,proto3" json:"not_cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_execution_engine_proto_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_engine_proto_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_execution_engine_proto_execution_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetNotCached() bool {
	if x != nil {
		return x.NotCached
	}
	return false
}

var File_execution_engine_proto_execution_proto protoreflect.FileDescriptor

const file_execution_engine_proto_execution_proto_rawDesc = "" +
	"\n" +
	"&execution_engine/proto/execution.proto\x12\texecution\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb4\x01\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12#\n" +
	"\rstate_msgpack\x18\x03 \x01(\fR\fstateMsgpack\x12'\n" +
	"\x0fsecrets_msgpack\x18\x04 \x01(\fR\x0esecretsMsgpack\x12'\n" +
	"\x0ftrigger_msgpack\x18\x05 \x01(\fR\x0etriggerMsgpack\"\x97\x01\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"not_cached\x18\x05 \x01(\bR\tnotCached2\x8c\x01\n" +
	"\x0fExecutionEngine\x127\n" +
	"\x04Ping\x12\x16.execution.PingRequest\x1a\x17.execution.PingResponse\x12@\n" +
	"\aExecute\x12\x19.execution.ExecuteRequest\x1a\x1a.execution.ExecuteResponseBSZQgithub.com/genazt/my-budget-script/web/backend/internal/service/proto;executionpbb\x06proto3"

var (
	file_execution_engine_proto_execution_proto_rawDescOnce sync.Once
	file_execution_engine_proto_execution_proto_rawDescData []byte
)

func file_execution_engine_proto_execution_proto_rawDescGZIP() []byte {
	file_execution_engine_proto_execution_proto_rawDescOnce.Do(func() {
		file_execution_engine_proto_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_engine_proto_execution_proto_rawDesc), len(file_execution_engine_proto_execution_proto_rawDesc)))
	})
	return file_execution_engine_proto_execution_proto_rawDescData
}

var file_execution_engine_proto_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_execution_engine_proto_execution_proto_goTypes = []any{
	(*PingRequest)(nil),     // 0: execution.PingRequest
	(*PingResponse)(nil),    // 1: execution.PingResponse
	(*ExecuteRequest)(nil),  // 2: execution.ExecuteRequest
	(*ExecuteResponse)(nil), // 3: execution.ExecuteResponse
}
var file_execution_engine_proto_execution_proto_depIdxs = []int32{
	0, // 0: execution.ExecutionEngine.Ping:input_type -> execution.PingRequest
	2, // 1: execution.ExecutionEngine.Execute:input_type -> execution.ExecuteRequest
	1, // 2: execution.ExecutionEngine.Ping:output_type -> execution.PingResponse
	3, // 3: execution.ExecutionEngine.Execute:output_type -> execution.ExecuteResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_execution_engine_proto_execution_proto_init() }
func file_execution_engine_proto_execution_proto_init() {
	if File_execution_engine_proto_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_engine_proto_execution_proto_rawDesc), len(file_execution_engine_proto_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_engine_proto_execution_proto_goTypes,
		DependencyIndexes: file_execution_engine_proto_execution_proto_depIdxs,
		MessageInfos:      file_execution_engine_proto_execution_proto_msgTypes,
	}.Build()
	File_execution_engine_proto_execution_proto = out.File
	file_execution_engine_proto_execution_proto_goTypes = nil
	file_execution_engine_proto_execution_proto_depIdxs = nil
}
