// Package enablebanking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package enablebanking

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetAspspsParamsPsuType.
const (
	Business GetAspspsParamsPsuType = "business"
	Personal GetAspspsParamsPsuType = "personal"
)

// Valid indicates whether the value is a known member of the GetAspspsParamsPsuType enum.
func (e GetAspspsParamsPsuType) Valid() bool {
	switch e {
	case Business:
		return true
	case Personal:
		return true
	default:
		return false
	}
}

// ASPSP defines model for ASPSP.
type ASPSP struct {
	Bic     *string `json:"bic,omitempty"`
	Country *string `json:"country,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// Account defines model for Account.
type Account struct {
	Currency *string `json:"currency,omitempty"`
	Iban     *string `json:"iban,omitempty"`
	Name     *string `json:"name,omitempty"`
	Uid      *string `json:"uid,omitempty"`
}

// AccountReference defines model for AccountReference.
type AccountReference struct {
	union json.RawMessage
}

// AccountReference0 defines model for .
type AccountReference0 = string

// AccountReference1 defines model for .
type AccountReference1 struct {
	Uid *string `json:"uid,omitempty"`
}

// Amount defines model for Amount.
type Amount struct {
	Amount   *string `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

// Balance defines model for Balance.
type Balance struct {
	BalanceAmount *Amount             `json:"balance_amount,omitempty"`
	Name          *string             `json:"name,omitempty"`
	ReferenceDate *openapi_types.Date `json:"reference_date,omitempty"`
}

// Counterparty defines model for Counterparty.
type Counterparty struct {
	Account *struct {
		Iban *string `json:"iban,omitempty"`
	} `json:"account,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	BankTransactionCode *struct {
		Code        *string `json:"code,omitempty"`
		Description *string `json:"description,omitempty"`
		SubCode     *string `json:"sub_code,omitempty"`
	} `json:"bank_transaction_code,omitempty"`
	BookingDate           *openapi_types.Date `json:"booking_date,omitempty"`
	CreditDebitIndicator  *string             `json:"credit_debit_indicator,omitempty"`
	Creditor              *Counterparty       `json:"creditor,omitempty"`
	Debtor                *Counterparty       `json:"debtor,omitempty"`
	EntryReference        *string             `json:"entry_reference,omitempty"`
	RemittanceInformation *[]string           `json:"remittance_information,omitempty"`
	Status                *string             `json:"status,omitempty"`
	TransactionAmount     *Amount             `json:"transaction_amount,omitempty"`
	TransactionId         *string             `json:"transaction_id,omitempty"`
	ValueDate             *openapi_types.Date `json:"value_date,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetAccountTransactionsParams defines parameters for GetAccountTransactions.
type GetAccountTransactionsParams struct {
	DateFrom                    *openapi_types.Date `form:"date_from,omitempty" json:"date_from,omitempty"`
	DateTo                      *openapi_types.Date `form:"date_to,omitempty" json:"date_to,omitempty"`
	ContinuationKey             *string             `form:"continuation_key,omitempty" json:"continuation_key,omitempty"`
	TransactionFetchingStrategy *string             `form:"transaction_fetching_strategy,omitempty" json:"transaction_fetching_strategy,omitempty"`
}

// GetAspspsParams defines parameters for GetAspsps.
type GetAspspsParams struct {
	Country *string                 `form:"country,omitempty" json:"country,omitempty"`
	PsuType *GetAspspsParamsPsuType `form:"psu_type,omitempty" json:"psu_type,omitempty"`
}

// GetAspspsParamsPsuType defines parameters for GetAspsps.
type GetAspspsParamsPsuType string

// StartAuthorizationJSONBody defines parameters for StartAuthorization.
type StartAuthorizationJSONBody struct {
	Access *struct {
		ValidUntil *time.Time `json:"valid_until,omitempty"`
	} `json:"access,omitempty"`
	Aspsp *struct {
		Country *string `json:"country,omitempty"`
		Name    *string `json:"name,omitempty"`
	} `json:"aspsp,omitempty"`
	PsuId       *string `json:"psu_id,omitempty"`
	RedirectUrl *string `json:"redirect_url,omitempty"`
	State       *string `json:"state,omitempty"`
}

// CreateSessionJSONBody defines parameters for CreateSession.
type CreateSessionJSONBody struct {
	Code *string `json:"code,omitempty"`
}

// StartAuthorizationJSONRequestBody defines body for StartAuthorization for application/json ContentType.
type StartAuthorizationJSONRequestBody StartAuthorizationJSONBody

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody CreateSessionJSONBody

// AsAccountReference0 returns the union data inside the AccountReference as a AccountReference0
func (t AccountReference) AsAccountReference0() (AccountReference0, error) {
	var body AccountReference0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAccountReference0 overwrites any union data inside the AccountReference as the provided AccountReference0
func (t *AccountReference) FromAccountReference0(v AccountReference0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAccountReference0 performs a merge with any union data inside the AccountReference, using the provided AccountReference0
func (t *AccountReference) MergeAccountReference0(v AccountReference0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAccountReference1 returns the union data inside the AccountReference as a AccountReference1
func (t AccountReference) AsAccountReference1() (AccountReference1, error) {
	var body AccountReference1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAccountReference1 overwrites any union data inside the AccountReference as the provided AccountReference1
func (t *AccountReference) FromAccountReference1(v AccountReference1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAccountReference1 performs a merge with any union data inside the AccountReference, using the provided AccountReference1
func (t *AccountReference) MergeAccountReference1(v AccountReference1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AccountReference) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AccountReference) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAccountBalances request
	GetAccountBalances(ctx context.Context, accountId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAccountDetails request
	GetAccountDetails(ctx context.Context, accountId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAccountTransactions request
	GetAccountTransactions(ctx context.Context, accountId string, params *GetAccountTransactionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAspsps request
	GetAspsps(ctx context.Context, params *GetAspspsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartAuthorizationWithBody request with any body
	StartAuthorizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	StartAuthorization(ctx context.Context, body StartAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSessionWithBody request with any body
	CreateSessionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateSession(ctx context.Context, body CreateSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSession request
	GetSession(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAccountBalances(ctx context.Context, accountId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountBalancesRequest(c.Server, accountId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAccountDetails(ctx context.Context, accountId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountDetailsRequest(c.Server, accountId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAccountTransactions(ctx context.Context, accountId string, params *GetAccountTransactionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountTransactionsRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAspsps(ctx context.Context, params *GetAspspsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAspspsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartAuthorizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartAuthorizationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartAuthorization(ctx context.Context, body StartAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartAuthorizationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSessionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSessionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSession(ctx context.Context, body CreateSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSessionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSession(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSessionRequest(c.Server, sessionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAccountBalancesRequest generates requests for GetAccountBalances
func NewGetAccountBalancesRequest(server string, accountId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s/balances", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAccountDetailsRequest generates requests for GetAccountDetails
func NewGetAccountDetailsRequest(server string, accountId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s/details", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAccountTransactionsRequest generates requests for GetAccountTransactions
func NewGetAccountTransactionsRequest(server string, accountId string, params *GetAccountTransactionsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s/transactions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.DateFrom != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "date_from", *params.DateFrom, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.DateTo != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "date_to", *params.DateTo, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ContinuationKey != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "continuation_key", *params.ContinuationKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.TransactionFetchingStrategy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "transaction_fetching_strategy", *params.TransactionFetchingStrategy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAspspsRequest generates requests for GetAspsps
func NewGetAspspsRequest(server string, params *GetAspspsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/aspsps")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Country != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "country", *params.Country, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PsuType != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "psu_type", *params.PsuType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartAuthorizationRequest calls the generic StartAuthorization builder with application/json body
func NewStartAuthorizationRequest(server string, body StartAuthorizationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStartAuthorizationRequestWithBody(server, "application/json", bodyReader)
}

// NewStartAuthorizationRequestWithBody generates requests for StartAuthorization with any type of body
func NewStartAuthorizationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateSessionRequest calls the generic CreateSession builder with application/json body
func NewCreateSessionRequest(server string, body CreateSessionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSessionRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateSessionRequestWithBody generates requests for CreateSession with any type of body
func NewCreateSessionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetSessionRequest generates requests for GetSession
func NewGetSessionRequest(server string, sessionId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "session_id", sessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAccountBalancesWithResponse request
	GetAccountBalancesWithResponse(ctx context.Context, accountId string, reqEditors ...RequestEditorFn) (*GetAccountBalancesResponse, error)

	// GetAccountDetailsWithResponse request
	GetAccountDetailsWithResponse(ctx context.Context, accountId string, reqEditors ...RequestEditorFn) (*GetAccountDetailsResponse, error)

	// GetAccountTransactionsWithResponse request
	GetAccountTransactionsWithResponse(ctx context.Context, accountId string, params *GetAccountTransactionsParams, reqEditors ...RequestEditorFn) (*GetAccountTransactionsResponse, error)

	// GetAspspsWithResponse request
	GetAspspsWithResponse(ctx context.Context, params *GetAspspsParams, reqEditors ...RequestEditorFn) (*GetAspspsResponse, error)

	// StartAuthorizationWithBodyWithResponse request with any body
	StartAuthorizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartAuthorizationResponse, error)

	StartAuthorizationWithResponse(ctx context.Context, body StartAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*StartAuthorizationResponse, error)

	// CreateSessionWithBodyWithResponse request with any body
	CreateSessionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSessionResponse, error)

	CreateSessionWithResponse(ctx context.Context, body CreateSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSessionResponse, error)

	// GetSessionWithResponse request
	GetSessionWithResponse(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*GetSessionResponse, error)
}

type GetAccountBalancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Balances *[]Balance `json:"balances,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetAccountBalancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountBalancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAccountBalancesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAccountDetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Account
}

// Status returns HTTPResponse.Status
func (r GetAccountDetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountDetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAccountDetailsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAccountTransactionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		ContinuationKey *string        `json:"continuation_key,omitempty"`
		Transactions    *[]Transaction `json:"transactions,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetAccountTransactionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountTransactionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAccountTransactionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAspspsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Aspsps *[]ASPSP `json:"aspsps,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetAspspsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAspspsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAspspsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StartAuthorizationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		AuthorizationId *string `json:"authorization_id,omitempty"`
		Url             *string `json:"url,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r StartAuthorizationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartAuthorizationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StartAuthorizationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateSessionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Accounts  *[]AccountReference `json:"accounts,omitempty"`
		SessionId *string             `json:"session_id,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateSessionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSessionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateSessionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSessionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Accounts  *[]AccountReference `json:"accounts,omitempty"`
		SessionId *string             `json:"session_id,omitempty"`
		Status    *string             `json:"status,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetSessionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSessionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSessionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetAccountBalancesWithResponse request returning *GetAccountBalancesResponse
func (c *ClientWithResponses) GetAccountBalancesWithResponse(ctx context.Context, accountId string, reqEditors ...RequestEditorFn) (*GetAccountBalancesResponse, error) {
	rsp, err := c.GetAccountBalances(ctx, accountId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountBalancesResponse(rsp)
}

// GetAccountDetailsWithResponse request returning *GetAccountDetailsResponse
func (c *ClientWithResponses) GetAccountDetailsWithResponse(ctx context.Context, accountId string, reqEditors ...RequestEditorFn) (*GetAccountDetailsResponse, error) {
	rsp, err := c.GetAccountDetails(ctx, accountId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountDetailsResponse(rsp)
}

// GetAccountTransactionsWithResponse request returning *GetAccountTransactionsResponse
func (c *ClientWithResponses) GetAccountTransactionsWithResponse(ctx context.Context, accountId string, params *GetAccountTransactionsParams, reqEditors ...RequestEditorFn) (*GetAccountTransactionsResponse, error) {
	rsp, err := c.GetAccountTransactions(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountTransactionsResponse(rsp)
}

// GetAspspsWithResponse request returning *GetAspspsResponse
func (c *ClientWithResponses) GetAspspsWithResponse(ctx context.Context, params *GetAspspsParams, reqEditors ...RequestEditorFn) (*GetAspspsResponse, error) {
	rsp, err := c.GetAspsps(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAspspsResponse(rsp)
}

// StartAuthorizationWithBodyWithResponse request with arbitrary body returning *StartAuthorizationResponse
func (c *ClientWithResponses) StartAuthorizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartAuthorizationResponse, error) {
	rsp, err := c.StartAuthorizationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartAuthorizationResponse(rsp)
}

func (c *ClientWithResponses) StartAuthorizationWithResponse(ctx context.Context, body StartAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*StartAuthorizationResponse, error) {
	rsp, err := c.StartAuthorization(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartAuthorizationResponse(rsp)
}

// CreateSessionWithBodyWithResponse request with arbitrary body returning *CreateSessionResponse
func (c *ClientWithResponses) CreateSessionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSessionResponse, error) {
	rsp, err := c.CreateSessionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSessionResponse(rsp)
}

func (c *ClientWithResponses) CreateSessionWithResponse(ctx context.Context, body CreateSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSessionResponse, error) {
	rsp, err := c.CreateSession(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSessionResponse(rsp)
}

// GetSessionWithResponse request returning *GetSessionResponse
func (c *ClientWithResponses) GetSessionWithResponse(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*GetSessionResponse, error) {
	rsp, err := c.GetSession(ctx, sessionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSessionResponse(rsp)
}

// ParseGetAccountBalancesResponse parses an HTTP response from a GetAccountBalancesWithResponse call
func ParseGetAccountBalancesResponse(rsp *http.Response) (*GetAccountBalancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountBalancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Balances *[]Balance `json:"balances,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAccountDetailsResponse parses an HTTP response from a GetAccountDetailsWithResponse call
func ParseGetAccountDetailsResponse(rsp *http.Response) (*GetAccountDetailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountDetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Account
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAccountTransactionsResponse parses an HTTP response from a GetAccountTransactionsWithResponse call
func ParseGetAccountTransactionsResponse(rsp *http.Response) (*GetAccountTransactionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountTransactionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			ContinuationKey *string        `json:"continuation_key,omitempty"`
			Transactions    *[]Transaction `json:"transactions,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAspspsResponse parses an HTTP response from a GetAspspsWithResponse call
func ParseGetAspspsResponse(rsp *http.Response) (*GetAspspsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAspspsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Aspsps *[]ASPSP `json:"aspsps,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseStartAuthorizationResponse parses an HTTP response from a StartAuthorizationWithResponse call
func ParseStartAuthorizationResponse(rsp *http.Response) (*StartAuthorizationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartAuthorizationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			AuthorizationId *string `json:"authorization_id,omitempty"`
			Url             *string `json:"url,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateSessionResponse parses an HTTP response from a CreateSessionWithResponse call
func ParseCreateSessionResponse(rsp *http.Response) (*CreateSessionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateSessionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Accounts  *[]AccountReference `json:"accounts,omitempty"`
			SessionId *string             `json:"session_id,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSessionResponse parses an HTTP response from a GetSessionWithResponse call
func ParseGetSessionResponse(rsp *http.Response) (*GetSessionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSessionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Accounts  *[]AccountReference `json:"accounts,omitempty"`
			SessionId *string             `json:"session_id,omitempty"`
			Status    *string             `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFfNbuQ2DH6VBdujG6ftzbdk+4NtDxt0AvQQDAxZ5mS0sSUtRQeYBn73QrJde2ON40lm257GI1Ek9fEj",
	"RT6BNLU1GjU7yJ7AyT3WInxebW42N/7DkrFIrDAsF0r6Hz5YhAwck9L30CYgTaOZDtE9LWqMbLTJsGKK",
	"TyjZi17JoGhuVzZEqGXcgCqEPsVyAo0qT/PoD9yhdyCoMxo/7iC7myt+7vZaO1tvqY5fXfyzPkf9OCqx",
	"u1yLSvRXeBbVbiMfTX1LuIMMvklHgqQ9O9Le0SV8aYArLwUHkZ2hWjBkEBaSNe6+92aQrCA+RGA5RpUj",
	"bIhZOIGZtyS0E5KV0TH89EPOo0QuTRmBeVidwVWik6TsoHy275oiP3I45mthzIPS92uxT0ASlorzEgvF",
	"udKlkoINxSkXRLvNJZJ8EbxwxeIVp9AXlZymyRfhWq2YA3+V7q7a46gYaxc90y8IIhHsOBbcHBGdhPXU",
	"/JiejVaCBB5F1bwhS7zvKBtSfNh48z0fURDSVcP78d8vg+rf/ryFpCv1XlO3O9raM1tovWKPZvBZceV3",
	"ftaiqPDdtdCeXe+ubj5AAo9ILsAN319cXlz6KxmLWlgFGfwYlhKwgvfBsbTPWpc+9V+5Ktu0rz9B5B4D",
	"wD5vQiA/lJDBr8h9Ib4eRL1WEjUykgu1WHknvCUYEhtGG+B58rlRhCVkTA32CIhYSm29sLNGu86lHy4v",
	"u/TVjF34hbWVTxJldPrJdWwb9UWLq/uCkUv8Gcr0jKeR8D8vHvDxd7/aJsegLpGFqtYg/VMv+T8GejEL",
	"+/fhFRhN0nYNULdT8a+IVtIr+9wgHUZtvlTkOzI1TA+/WEkWlLE5hyofRaWbgFj+gAd4xd2mBXSHLPf+",
	"WXNMgvF+WeF5c3h2lxdeivXJPu0r3prwzjq7TNhOIs7RWfi6jv4VUbOuyYPo9CzqpobsDiySM1pUkEDR",
	"OKXROdgmXzl+IzSrgtINP28NR//8WuMi0diwIPYvtCH1V9exdLUAHV+b8vCWy0rpQZ2tP4pKlXmjWVWz",
	"tP6OVb2yLQ9YxlLkLBOg586RVsl3noSS84aqeJvMfRv1ctvUtufl1zSQx/yPu30aqRw6N9SXOLHeEwrG",
	"TSd3Nk6tnj7Ojmz/Qq/P3ecDe6zd79DJV07nawKSPo1K26UaPEbm5UZh4ud/17/++xFYmMdOCM5kNAr4",
	"Toeiu60HySE9DuiH5AzDj8vSVFh1gWHcKbpp50KaGtpt+3cAAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
