// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: execution.proto

package executionpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionEngine_Ping_FullMethodName    = "/execution.ExecutionEngine/Ping"
	ExecutionEngine_Execute_FullMethodName = "/execution.ExecutionEngine/Execute"
)

// ExecutionEngineClient is the client API for ExecutionEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionEngineClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type executionEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionEngineClient(cc grpc.ClientConnInterface) ExecutionEngineClient {

	return &executionEngineClient{cc}
}

func (c *executionEngineClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {

	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ExecutionEngine_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionEngineClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {

	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ExecutionEngine_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionEngineServer is the server API for ExecutionEngine service.
// All implementations must embed UnimplementedExecutionEngineServer
// for forward compatibility.
type ExecutionEngineServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedExecutionEngineServer()
}

// UnimplementedExecutionEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionEngineServer struct{}

func (UnimplementedExecutionEngineServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {

	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedExecutionEngineServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {

	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedExecutionEngineServer) mustEmbedUnimplementedExecutionEngineServer() {}
func (UnimplementedExecutionEngineServer) testEmbeddedByValue()                         {}

// UnsafeExecutionEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionEngineServer will
// result in compilation errors.
type UnsafeExecutionEngineServer interface {
	mustEmbedUnimplementedExecutionEngineServer()
}

func RegisterExecutionEngineServer(s grpc.ServiceRegistrar, srv ExecutionEngineServer) {

	// If the following call panics, it indicates UnimplementedExecutionEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionEngine_ServiceDesc, srv)
}

func _ExecutionEngine_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionEngineServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionEngine_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionEngineServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionEngine_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionEngineServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionEngine_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionEngineServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionEngine_ServiceDesc is the grpc.ServiceDesc for ExecutionEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execution.ExecutionEngine",
	HandlerType: (*ExecutionEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ExecutionEngine_Ping_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _ExecutionEngine_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "execution.proto",
}
