// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: execution.proto

package executionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExecuteRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CorrelationId string                  `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	PlanId        string                  `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Code          string                  `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CodeHash      string                  `protobuf:"bytes,4,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	StateJson     []byte                  `protobuf:"bytes,5,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	Secrets       map[string]string       `protobuf:"bytes,6,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Trigger       *ExecuteRequest_Trigger `protobuf:"bytes,7,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ExecuteRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetCodeHash() string {
	if x != nil {
		return x.CodeHash
	}
	return ""
}

func (x *ExecuteRequest) GetStateJson() []byte {
	if x != nil {
		return x.StateJson
	}
	return nil
}

func (x *ExecuteRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ExecuteRequest) GetTrigger() *ExecuteRequest_Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ParamsJson    []byte                 `protobuf:"bytes,4,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{4}
}

func (x *RpcRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RpcRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RpcRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,4,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{5}
}

func (x *RpcResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RpcResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RpcResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RpcResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *RpcResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StdioFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StdioFrame_ExecuteRequest
	//	*StdioFrame_ExecuteResponse
	//	*StdioFrame_RpcRequest
	//	*StdioFrame_RpcResponse
	//	*StdioFrame_PingRequest
	//	*StdioFrame_PingResponse
	Message       isStdioFrame_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdioFrame) Reset() {
	*x = StdioFrame{}
	mi := &file_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioFrame) ProtoMessage() {}

func (x *StdioFrame) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioFrame.ProtoReflect.Descriptor instead.
func (*StdioFrame) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{6}
}

func (x *StdioFrame) GetMessage() isStdioFrame_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StdioFrame) GetExecuteRequest() *ExecuteRequest {
	if x != nil {
		if x, ok := x.Message.(*StdioFrame_ExecuteRequest); ok {
			return x.ExecuteRequest
		}
	}
	return nil
}

func (x *StdioFrame) GetExecuteResponse() *ExecuteResponse {
	if x != nil {
		if x, ok := x.Message.(*StdioFrame_ExecuteResponse); ok {
			return x.ExecuteResponse
		}
	}
	return nil
}

func (x *StdioFrame) GetRpcRequest() *RpcRequest {
	if x != nil {
		if x, ok := x.Message.(*StdioFrame_RpcRequest); ok {
			return x.RpcRequest
		}
	}
	return nil
}

func (x *StdioFrame) GetRpcResponse() *RpcResponse {
	if x != nil {
		if x, ok := x.Message.(*StdioFrame_RpcResponse); ok {
			return x.RpcResponse
		}
	}
	return nil
}

func (x *StdioFrame) GetPingRequest() *PingRequest {
	if x != nil {
		if x, ok := x.Message.(*StdioFrame_PingRequest); ok {
			return x.PingRequest
		}
	}
	return nil
}

func (x *StdioFrame) GetPingResponse() *PingResponse {
	if x != nil {
		if x, ok := x.Message.(*StdioFrame_PingResponse); ok {
			return x.PingResponse
		}
	}
	return nil
}

type isStdioFrame_Message interface {
	isStdioFrame_Message()
}

type StdioFrame_ExecuteRequest struct {
	ExecuteRequest *ExecuteRequest `protobuf:"bytes,1,opt,name=execute_request,json=executeRequest,proto3,oneof"`
}

type StdioFrame_ExecuteResponse struct {
	ExecuteResponse *ExecuteResponse `protobuf:"bytes,2,opt,name=execute_response,json=executeResponse,proto3,oneof"`
}

type StdioFrame_RpcRequest struct {
	RpcRequest *RpcRequest `protobuf:"bytes,3,opt,name=rpc_request,json=rpcRequest,proto3,oneof"`
}

type StdioFrame_RpcResponse struct {
	RpcResponse *RpcResponse `protobuf:"bytes,4,opt,name=rpc_response,json=rpcResponse,proto3,oneof"`
}

type StdioFrame_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,5,opt,name=ping_request,json=pingRequest,proto3,oneof"`
}

type StdioFrame_PingResponse struct {
	PingResponse *PingResponse `protobuf:"bytes,6,opt,name=ping_response,json=pingResponse,proto3,oneof"`
}

func (*StdioFrame_ExecuteRequest) isStdioFrame_Message() {}

func (*StdioFrame_ExecuteResponse) isStdioFrame_Message() {}

func (*StdioFrame_RpcRequest) isStdioFrame_Message() {}

func (*StdioFrame_RpcResponse) isStdioFrame_Message() {}

func (*StdioFrame_PingRequest) isStdioFrame_Message() {}

func (*StdioFrame_PingResponse) isStdioFrame_Message() {}

type ExecuteRequest_Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest_Trigger) Reset() {
	*x = ExecuteRequest_Trigger{}
	mi := &file_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest_Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest_Trigger) ProtoMessage() {}

func (x *ExecuteRequest_Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest_Trigger.ProtoReflect.Descriptor instead.
func (*ExecuteRequest_Trigger) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ExecuteRequest_Trigger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecuteRequest_Trigger) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

var File_execution_proto protoreflect.FileDescriptor

const file_execution_proto_rawDesc = "" +
	"\n" +
	"\x0fexecution.proto\x12\texecution\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x97\x03\n" +
	"\x0eExecuteRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1b\n" +
	"\tcode_hash\x18\x04 \x01(\tR\bcodeHash\x12\x1d\n" +
	"\n" +
	"state_json\x18\x05 \x01(\fR\tstateJson\x12@\n" +
	"\asecrets\x18\x06 \x03(\v2&.execution.ExecuteRequest.SecretsEntryR\asecrets\x12;\n" +
	"\atrigger\x18\a \x01(\v2!.execution.ExecuteRequest.TriggerR\atrigger\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\aTrigger\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\"\x9f\x01\n" +
	"\x0fExecuteResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\"\x83\x01\n" +
	"\n" +
	"RpcRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1f\n" +
	"\vparams_json\x18\x04 \x01(\fR\n" +
	"paramsJson\"\x9c\x01\n" +
	"\vRpcResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x04 \x01(\fR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x9a\x03\n" +
	"\n" +
	"StdioFrame\x12D\n" +
	"\x0fexecute_request\x18\x01 \x01(\v2\x19.execution.ExecuteRequestH\x00R\x0eexecuteRequest\x12G\n" +
	"\x10execute_response\x18\x02 \x01(\v2\x1a.execution.ExecuteResponseH\x00R\x0fexecuteResponse\x128\n" +
	"\vrpc_request\x18\x03 \x01(\v2\x15.execution.RpcRequestH\x00R\n" +
	"rpcRequest\x12;\n" +
	"\frpc_response\x18\x04 \x01(\v2\x16.execution.RpcResponseH\x00R\vrpcResponse\x12;\n" +
	"\fping_request\x18\x05 \x01(\v2\x16.execution.PingRequestH\x00R\vpingRequest\x12>\n" +
	"\rping_response\x18\x06 \x01(\v2\x17.execution.PingResponseH\x00R\fpingResponseB\t\n" +
	"\amessage2\x8c\x01\n" +
	"\x0fExecutionEngine\x127\n" +
	"\x04Ping\x12\x16.execution.PingRequest\x1a\x17.execution.PingResponse\x12@\n" +
	"\aExecute\x12\x19.execution.ExecuteRequest\x1a\x1a.execution.ExecuteResponseBSZQgithub.com/genazt/my-budget-script/web/backend/internal/service/proto;executionpbb\x06proto3"

var (
	file_execution_proto_rawDescOnce sync.Once
	file_execution_proto_rawDescData []byte
)

func file_execution_proto_rawDescGZIP() []byte {
	file_execution_proto_rawDescOnce.Do(func() {
		file_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)))
	})
	return file_execution_proto_rawDescData
}

var file_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_execution_proto_goTypes = []any{
	(*PingRequest)(nil),            // 0: execution.PingRequest
	(*PingResponse)(nil),           // 1: execution.PingResponse
	(*ExecuteRequest)(nil),         // 2: execution.ExecuteRequest
	(*ExecuteResponse)(nil),        // 3: execution.ExecuteResponse
	(*RpcRequest)(nil),             // 4: execution.RpcRequest
	(*RpcResponse)(nil),            // 5: execution.RpcResponse
	(*StdioFrame)(nil),             // 6: execution.StdioFrame
	nil,                            // 7: execution.ExecuteRequest.SecretsEntry
	(*ExecuteRequest_Trigger)(nil), // 8: execution.ExecuteRequest.Trigger
}
var file_execution_proto_depIdxs = []int32{
	7,  // 0: execution.ExecuteRequest.secrets:type_name -> execution.ExecuteRequest.SecretsEntry
	8,  // 1: execution.ExecuteRequest.trigger:type_name -> execution.ExecuteRequest.Trigger
	2,  // 2: execution.StdioFrame.execute_request:type_name -> execution.ExecuteRequest
	3,  // 3: execution.StdioFrame.execute_response:type_name -> execution.ExecuteResponse
	4,  // 4: execution.StdioFrame.rpc_request:type_name -> execution.RpcRequest
	5,  // 5: execution.StdioFrame.rpc_response:type_name -> execution.RpcResponse
	0,  // 6: execution.StdioFrame.ping_request:type_name -> execution.PingRequest
	1,  // 7: execution.StdioFrame.ping_response:type_name -> execution.PingResponse
	0,  // 8: execution.ExecutionEngine.Ping:input_type -> execution.PingRequest
	2,  // 9: execution.ExecutionEngine.Execute:input_type -> execution.ExecuteRequest
	1,  // 10: execution.ExecutionEngine.Ping:output_type -> execution.PingResponse
	3,  // 11: execution.ExecutionEngine.Execute:output_type -> execution.ExecuteResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_execution_proto_init() }
func file_execution_proto_init() {
	if File_execution_proto != nil {
		return
	}
	file_execution_proto_msgTypes[6].OneofWrappers = []any{
		(*StdioFrame_ExecuteRequest)(nil),
		(*StdioFrame_ExecuteResponse)(nil),
		(*StdioFrame_RpcRequest)(nil),
		(*StdioFrame_RpcResponse)(nil),
		(*StdioFrame_PingRequest)(nil),
		(*StdioFrame_PingResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_proto_goTypes,
		DependencyIndexes: file_execution_proto_depIdxs,
		MessageInfos:      file_execution_proto_msgTypes,
	}.Build()
	File_execution_proto = out.File
	file_execution_proto_goTypes = nil
	file_execution_proto_depIdxs = nil
}
